name: NodeJS with Rollup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        version: "latest"
        run_install: "true"  # 自动运行 pnpm install

    - name: Run Rollup Build
      run: pnpm run build  # 执行构建命令

    - name: 查看构建后的文件
      run: ls -la dist  # 列出 dist 目录内容
      
    - name: 上传构建结果为 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: dist/  # 指定要上传的目录或文件路径
